//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-8QO6SORRF20\\MSSQL2012EXPRESS;Initial Catalog=TamizajeDB;Integrate" +
            "d Security=True")]
        public string TamizajeDBConnectionString {
            get {
                return ((string)(this["TamizajeDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-8QO6SORRF20\\MSSQL2012EXPRESS;Initial Catalog=TamizajeDB_Beta1.0;I" +
            "ntegrated Security=True")]
        public string TamizajeDB_Beta1_0ConnectionString {
            get {
                return ((string)(this["TamizajeDB_Beta1_0ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LENOVO-PC;Initial Catalog=TamizajeDB_Beta1.0;Integrated Security=True" +
            "")]
        public string TamizajeDB_Beta1_0ConnectionString1 {
            get {
                return ((string)(this["TamizajeDB_Beta1_0ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PV-CESAR\\MSSQL2012;Initial Catalog=TamizajeDB_Beta1.0;Integrated Secu" +
            "rity=True")]
        public string TamizajeDB_Beta1_0ConnectionString2 {
            get {
                return ((string)(this["TamizajeDB_Beta1_0ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PV-CESAR\\MSSQL2012;Initial Catalog=TamizajeDB_Quick;Integrated Securi" +
            "ty=True")]
        public string TamizajeDB_QuickConnectionString {
            get {
                return ((string)(this["TamizajeDB_QuickConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PV-CESAR\\MSSQL2012;Initial Catalog=DBEssalud;Integrated Security=True" +
            "")]
        public string DBEssaludConnectionString {
            get {
                return ((string)(this["DBEssaludConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN7-PC\\SQLEXPRESS2012;Initial Catalog=DBEssalud;Integrated Security=" +
            "True")]
        public string DBEssaludConnectionString1 {
            get {
                return ((string)(this["DBEssaludConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN7-PC\\SQLEXPRESS2012;Initial Catalog=TamiLifeSA;Integrated Security" +
            "=True")]
        public string TamiLifeSAConnectionString {
            get {
                return ((string)(this["TamiLifeSAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HCUKI4I\\SQLEXPRESS2012;Initial Catalog=TamiLifeSA;Integrated " +
            "Security=True")]
        public string TamiLifeSAConnectionString1 {
            get {
                return ((string)(this["TamiLifeSAConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MAYRALAPTOP\\SQLEXPRESS2012;Initial Catalog=TamiLifeSA;Integrated Secu" +
            "rity=True")]
        public string TamiLifeSAConnectionString2 {
            get {
                return ((string)(this["TamiLifeSAConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN7-PC\\SQLEXPRESS2012;Initial Catalog=TamiLifeINMP;Integrated Securi" +
            "ty=True")]
        public string TamiLifeINMPConnectionString {
            get {
                return ((string)(this["TamiLifeINMPConnectionString"]));
            }
        }
    }
}
